### ISSUE TITLE
Upgrade proto dependencies

### ISSUE THREAD

**Issue by Eistern** [ydb-platform/ydb-java-genproto#2]
Currently, ydb-proto-api brings in grpc dependency with an active bug

https://github.com/grpc/grpc-java/issues/9340

However, it was fixed in the 1.49 release and back ported to 1.47.x
So please update grpc.version in pom.xml if possible

**Comment by alex268** [comment]
Yes, we know about this issue and grpc retries [are disabled](https://github.com/ydb-platform/ydb-java-sdk/blob/master/core/src/main/java/tech/ydb/core/grpc/GrpcTransportBuilder.java#L53) by default now. We are planning to update the version of grpc-java in the nearest future

**Comment by alex268** [comment]
Fixed [here](https://github.com/ydb-platform/ydb-java-genproto/commit/b2a86da0ccfcbe45cf31177d19d199093b59b715)
